version: '0.0.1'

services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_USER: smsa
      MYSQL_PASSWORD: "@smsa2022"
      MYSQL_DATABASE: fastshop
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: "#smsr2022"
    ports:
      - "3306:3306"
  sms:
    build: .
    tty: true
    ports:
      - "3000:3000"
