version: '0.0.1'

services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: '@sms2022'
    ports:
      - "3306:3306"
  sms:
    build: .
    tty: true
    ports:
      - "3000:3000"